spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
#    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  session:
    store-type: jdbc
    timeout: 10